spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: C##gotrip
    password: gotrip
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  messages:
    basename: messages

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  servlet:
    session:
      timeout: 60m
